Repository ccache/ccache, pull requests merged in 2019-01, with the labels that each got.

#341 Add missing getopt_long.c source file to dist
  dev.mk.in
Labels: bug

#301 Add depend mode (avoid the preprocessor)
  doc/MANUAL.adoc
  src/ccache.c
  src/conf.c
  src/conf.h
  src/confitems.gperf
  src/confitems_lookup.c
  src/envtoconfitems.gperf
  src/envtoconfitems_lookup.c
  test/run
  test/suites/depend.bash
  unittest/test_conf.c
Labels: enhancement

#278 Improvement and upgrade of Docker build
  base/README
  base/alpine/Dockerfile
  base/centos/Dockerfile
  base/debian/Dockerfile
  base/fedora/Dockerfile
  base/ubuntu/Dockerfile
  dev.mk.in
  misc/build.sh
Labels: enhancement

#346 Try to fix link to cache debugging
  doc/MANUAL.adoc
Labels: documentation

#345 Spelling
  src/ccache.c
  src/compopt.c
  src/conf.c
  unittest/test_argument_processing.c
  unittest/test_compopt.c
Labels: improvement

#329 Fix the build on IBM i / PASE
  configure.ac
  src/lockfile.c
  src/system.h
Labels: portability
