Repository ccache/ccache, pull requests merged in 2019-10, with the labels that each got.

#475 Fix an out-of-bounds read when logging
  src/result.cpp
Labels: bug

#477 Test output: visibility on light backgrounds / ansi codes
  test/run
Labels: improvement

#479 Fix warning during configure in out of tree build
  configure.ac
Labels: bug, build

#478 Convert result type string to an enum
  src/ccache.cpp
  src/result.cpp
  src/result.hpp
Labels: improvement

#476 Add AVX2 variant of check_for_temporal_macros
  configure.ac
  src/hashutil.cpp
  unittest/test_hashutil.cpp
Labels: feature
