Repository ccache/ccache, pull requests merged in 2019-12, with the labels that each got.

#483 Misc C++-ification
  src/Config.hpp
  src/Util.cpp
  src/Util.hpp
  src/ccache.cpp
  src/ccache.hpp
  src/execute.cpp
  src/hash.cpp
  src/hash.hpp
  src/legacy_util.cpp
  unittest/test_Config.cpp
  unittest/test_Config.hpp
  unittest/test_Util.cpp
  unittest/test_legacy_util.cpp
Labels: improvement

#495 Store mtime/ctime as -1 if sloppy_file_stat is not set
  src/ccache.c
  src/manifest.c
  src/manifest.h
Labels: bug

#496 Unittest fixes on Windows
  unittest/test_Config.cpp
  unittest/test_ZstdCompression.cpp
Labels: improvement, portability, windows
