Repository ccache/ccache, pull requests merged in 2019-04, with the labels that each got.

#370 Include the presence of "-fxxx-prefix-map=" options in the hash
  src/ccache.c
Labels: bug

#379 Copy rather than link depend from the cache
  src/ccache.c
  test/suites/hardlink.bash
Labels: feature

#280 Add optional support for microsecond tracing
  LICENSE.adoc
  Makefile.in
  configure.ac
  dev.mk.in
  doc/DEVELOPER.md
  misc/combine_events.py
  misc/summarize_events.py
  src/ccache.c
  src/ccache.h
  src/minitrace.c
  src/minitrace.h
  src/util.c
Labels: feature

#392 correctly handle @file syntax on Windows
  src/ccache.h
  src/execute.c
  src/hashutil.c
Labels: bug, windows

#395 Fix NULL argument in profile directory trace
  src/ccache.c
Labels: bug

#398 Support using -MF /dev/null argument
  src/ccache.c
  test/suites/depend.bash
  test/suites/direct.bash
Labels: bug
