Repository ccache/ccache, pull requests merged in 2019-11, with the labels that each got.

#481 Fix and test interaction between fmt and nonstd::string_view
  src/FormatNonstdStringView.hpp
  unittest/test_Util.cpp
Labels: bug

#486 Correct "-MJ" bail out, identify both "-MJ file" and "-MJfile"
  src/ccache.c
  src/compopt.c
  unittest/test_compopt.c
Labels: bug

#487 Correct "-MJ" bail out, identify both "-MJ file" and "-MJfile"
  src/ccache.cpp
  src/compopt.cpp
  unittest/test_compopt.cpp
Labels: bug

#482 Allow -fmodules in direct depend mode
  doc/MANUAL.adoc
  src/Config.cpp
  src/ccache.cpp
  src/ccache.hpp
  src/compopt.cpp
  src/stats.cpp
  test/run
  test/suites/modules.bash
Labels: feature

#484 Handle properly color diagnostics also in depend mode
  src/ccache.cpp
Labels: bug

#492 Windows define and include restructuring
  src/CacheEntryWriter.hpp
  src/CacheFile.hpp
  src/Compressor.hpp
  src/File.hpp
  src/FormatNonstdStringView.hpp
  src/NullCompressor.hpp
  src/NullDecompressor.hpp
  src/ProgressBar.cpp
  src/ProgressBar.hpp
  src/cleanup.hpp
  src/compress.hpp
  src/legacy_util.cpp
  src/system.hpp
Labels: improvement
