Repository ccache/ccache, pull requests merged in 2019-05, with the labels that each got.

#403 Misc. source comment and documentation typos
  doc/DEVELOPER.md
  doc/NEWS.adoc
  src/conf.c
Labels: documentation, improvement

#409 Implement optional logging to syslog
  configure.ac
  doc/MANUAL.adoc
  misc/rsyslog.d/00-ccache.conf
  src/util.c
Labels: feature

#420 Fix make check with "funny" locales
  test/run
Labels: bug

#424 clang's -ftime-trace is too hard
  src/compopt.c
Labels: unhandled compiler behavior

#427 Fix PCH detection in depend mode (+test improvements)
  doc/MANUAL.adoc
  src/ccache.c
  test/suites/pch.bash
Labels: bug

#408 Add aggregated file storing all the results
  Makefile.in
  configure.ac
  src/ccache.c
  src/result.c
  src/result.h
  test/suites/base.bash
  test/suites/cleanup.bash
  test/suites/depend.bash
  test/suites/direct.bash
  test/suites/serialize_diagnostics.bash
  test/suites/split_dwarf.bash
Labels: feature

#428 Refactor: save tmp stderr until done storing
  src/ccache.c
Labels: improvement
