Repository ccache/ccache, pull requests merged in 2020-06, with the labels that each got.

#604 Documentation change for cache over NFS
  doc/MANUAL.adoc
Labels: documentation, improvement

#606 Docker: add Alpine to new docker setup
  buildenv/alpine-3.12/Dockerfile
  buildenv/alpine-3.4/Dockerfile
  buildenv/alpine/Dockerfile
  cmake/StandardWarnings.cmake
  test-all-systems.sh
Labels: build, improvement, portability

#519 Replace BLAKE2b with BLAKE3
  .travis.yml
  CMakeLists.txt
  LICENSE.adoc
  cmake/Findlibb2.cmake
  cmake/Libb2CMakeLists.txt
  cmake/StandardWarnings.cmake
  doc/INSTALL.md
  doc/MANUAL.adoc
  doc/NEWS.adoc
  dockerfiles/debian-10-buster/Dockerfile
  dockerfiles/debian-9-stretch/Dockerfile
  dockerfiles/travis/Dockerfile
  dockerfiles/ubuntu-16-xenial/Dockerfile
  dockerfiles/ubuntu-20-focal/Dockerfile
  src/CMakeLists.txt
  src/InodeCache.cpp
  src/ccache.cpp
  src/hash.cpp
  src/third_party/CMakeLists.txt
  src/third_party/blake3/CMakeLists.txt
  src/third_party/blake3/blake3.c
  src/third_party/blake3/blake3.h
  src/third_party/blake3/blake3_avx2.c
  src/third_party/blake3/blake3_avx2_x86-64_unix.S
  src/third_party/blake3/blake3_avx2_x86-64_windows_gnu.S
  src/third_party/blake3/blake3_avx512.c
  src/third_party/blake3/blake3_avx512_x86-64_unix.S
  src/third_party/blake3/blake3_avx512_x86-64_windows_gnu.S
  src/third_party/blake3/blake3_dispatch.c
  src/third_party/blake3/blake3_impl.h
  src/third_party/blake3/blake3_neon.c
  src/third_party/blake3/blake3_portable.c
  src/third_party/blake3/blake3_sse41.c
  src/third_party/blake3/blake3_sse41_x86-64_unix.S
  src/third_party/blake3/blake3_sse41_x86-64_windows_gnu.S
  test-all-systems.sh
  test/suites/base.bash
  test/suites/direct.bash
  unittest/test_hash.cpp
Labels: improvement

#608 Reduce number of memory allocations in hashing
  src/InodeCache.cpp
  src/hash.cpp
  src/hash.hpp
  unittest/test_hash.cpp
Labels: improvement

#609 Do not report skipped tests as failures on CMake <3.9
  dockerfiles/alpine-3.4/Dockerfile
  dockerfiles/alpine/Dockerfile
  test-all-systems.sh
  test/CMakeLists.txt
Labels: build, portability
