Repository ccache/ccache, pull requests merged in 2020-08, with the labels that each got.

#636 Util::unlink_tmp: Log with correct errno
  src/Util.cpp
Labels: bug

#637 Update comments, remove references to old global variables
  src/Logging.cpp
  src/ccache.cpp
  src/stats.cpp
Labels: improvement

#640 Fix override usage
  src/ResultDumper.hpp
  src/ResultExtractor.hpp
  src/ResultRetriever.hpp
  src/third_party/fmt/core.h
Labels: build, portability

#644 Fix asm compiler detection
  CMakeLists.txt
Labels: build, portability

#632 Support building on MSVC.
  .gitignore
  CMakeLists.txt
  LGPL-3.0.txt
  LICENSE.adoc
  cmake/GenerateConfigurationFile.cmake
  cmake/StandardSettings.cmake
  cmake/StandardWarnings.cmake
  cmake/config.h.in
  misc/format-files
  src/Args.cpp
  src/CMakeLists.txt
  src/Lockfile.cpp
  src/ProgressBar.cpp
  src/Result.cpp
  src/Util.cpp
  src/Util.hpp
  src/Win32Util.cpp
  src/ZstdCompressor.cpp
  src/ccache.cpp
  src/system.hpp
  src/third_party/CMakeLists.txt
  src/third_party/win32/getopt.c
  src/third_party/win32/getopt.h
  test/CMakeLists.txt
  unittest/TestUtil.hpp
  unittest/test_Stat.cpp
  unittest/test_Util.cpp
  unittest/test_argprocessing.cpp
Labels: build, portability, windows

#647 Merge address and UB sanitizer
  .github/workflows/build.yaml
  cmake/StandardSettings.cmake
Labels: ci

#648 Skipped test on NFS #639
  test/suites/inode_cache.bash
Labels: build, portability
