Repository ccache/ccache, pull requests merged in 2020-09, with the labels that each got.

#650 Add Visual Studio build directory to gitignore
  .gitignore
Labels: build

#651 Refactoring: convert stats to enum class
  src/Counters.cpp
  src/Counters.hpp
  src/argprocessing.cpp
  src/argprocessing.hpp
  src/ccache.cpp
  src/exceptions.hpp
  src/stats.cpp
  src/stats.hpp
  unittest/test_argprocessing.cpp
Labels: improvement

#652 Refactoring: use return syntax for process_args
  src/argprocessing.cpp
  src/argprocessing.hpp
  src/ccache.cpp
  unittest/test_argprocessing.cpp
Labels: improvement

#657 Switch from XXH64 to XXH3 for checksums
  LICENSE.adoc
  doc/MANUAL.adoc
  doc/NEWS.adoc
  src/Checksum.hpp
  src/Manifest.cpp
  src/Result.cpp
  src/ccache.cpp
  src/third_party/CMakeLists.txt
  src/third_party/xxh_x86dispatch.c
  src/third_party/xxh_x86dispatch.h
  src/third_party/xxhash.c
  src/third_party/xxhash.h
  unittest/CMakeLists.txt
  unittest/test_Checksum.cpp
Labels: improvement

#658 Tests: Compare relevant part, not internal state
  unittest/test_argprocessing.cpp
Labels: improvement

#659 Test: introduce unit test for -Xclang argument
  unittest/test_argprocessing.cpp
Labels: improvement

#661 Refactor: convert Util function to use string_view
  src/Util.cpp
  src/Util.hpp
Labels: improvement

#666 Add support for hip language
  src/ccache.cpp
  src/language.cpp
  test/CMakeLists.txt
  test/suites/profiling_hip_clang.bash
Labels: feature

#669 Small fixes for the master branch
  src/TemporaryFile.hpp
  src/execute.cpp
Labels: bug

#670 Add unittest for find_compiler
  src/Config.hpp
  src/Util.cpp
  src/Util.hpp
  src/ccache.cpp
  src/ccache.hpp
  unittest/CMakeLists.txt
  unittest/test_ccache.cpp
Labels: improvement

#673 Add error detection to zstd download
  cmake/Findzstd.cmake
Labels: build, improvement
