Repository ccache/ccache, pull requests merged in 2020-04, with the labels that each got.

#576 Fix #559 (setting base_dir and cache_dir_levels)
  src/conf.c
Labels: bug

#562 Enable check_format and clang-tidy checks in CI
  .clang-tidy
  .travis.sh
  .travis.yml
  src/.clang-tidy
  src/Counters.cpp
  src/logging.cpp
  src/third_party/.clang-tidy
  unittest/.clang-tidy
Labels: improvement

#572 Make ccache build on Solaris 11.4
  m4/feature_macros.m4
  src/ProgressBar.cpp
Labels: bug, build, portability

#575 Add an Args class with backward compatibility for the old args API
  Makefile.in
  configure.ac
  src/Args.cpp
  src/Args.hpp
  src/ArgsInfo.cpp
  src/ArgsInfo.hpp
  src/Context.cpp
  src/Context.hpp
  src/args.cpp
  src/args.hpp
  src/ccache.cpp
  src/ccache.hpp
  src/hashutil.cpp
  unittest/framework.cpp
  unittest/framework.hpp
  unittest/test_Args.cpp
  unittest/test_args.cpp
  unittest/test_argument_processing.cpp
  unittest/test_legacy_args.cpp
Labels: improvement

#580 Diverse CMake preparations
  .gitignore
  .travis.yml
  buildenv/alpine/Dockerfile
  buildenv/centos/Dockerfile
  buildenv/debian-10-buster/Dockerfile
  buildenv/debian-9-stretch/Dockerfile
  buildenv/debian/Dockerfile
  buildenv/fedora/Dockerfile
  buildenv/travis/Dockerfile
  buildenv/ubuntu-16-xenial/Dockerfile
  buildenv/ubuntu/Dockerfile
  doc/AUTHORS.adoc
  doc/INSTALL.md
  misc/install_cuda.sh
  misc/update_authors.sh
  src/Args.cpp
  src/Args.hpp
Labels: build, improvement, portability

#583 Add test for human readable version output
  test/suites/base.bash
Labels: improvement

#585 Extract formatting logic from make.
  dev.mk.in
  misc/check_format.sh
  misc/format.sh
  misc/run-clang-format
Labels: improvement
