Repository ccache/ccache, pull requests merged in 2020-12, with the labels that each got.

#730 Unbreak FreeBSD build
  cmake/config.h.in
Labels: bug, build, portability

#735 Improve simd detection
  cmake/GenerateConfigurationFile.cmake
  src/third_party/blake3/CMakeLists.txt
Labels: bug, build, portability

#743 Fix building 32bit tests on macOS
  src/third_party/doctest.h
Labels: bug, build, portability

#744 Add missing pragma once
  src/Depfile.hpp
Labels: build, improvement

#736 Make TemporaryFile generate unique file names on Windows
  LICENSE.adoc
  src/TemporaryFile.cpp
  src/third_party/CMakeLists.txt
  src/third_party/win32/mktemp.c
  src/third_party/win32/mktemp.h
  unittest/CMakeLists.txt
  unittest/test_bsdmkstemp.cpp
Labels: bug, windows

#756 Fix running tests on macOS
  misc/format-files
  test/run
  test/suites/base.bash
  test/suites/cache_levels.bash
Labels: ci, portability
