Repository ccache/ccache, pull requests merged in 2020-02, with the labels that each got.

#535 Win32: Close reading file for recompression
  src/compress.cpp
  src/legacy_util.cpp
Labels: bug

#532 Move logging into separate file
  Makefile.in
  src/Stat.cpp
  src/ZstdCompressor.cpp
  src/ccache.cpp
  src/cleanup.cpp
  src/execute.cpp
  src/exitfn.cpp
  src/hash.cpp
  src/hashutil.cpp
  src/legacy_util.cpp
  src/legacy_util.hpp
  src/lockfile.cpp
  src/logging.cpp
  src/logging.hpp
  src/manifest.cpp
  src/result.hpp
  src/stats.cpp
Labels: improvement

#534 Extract setup_config() from initialize()
  src/ccache.cpp
Labels: improvement

#546 Restore test suite debug output where needed
  test/suites/fileclone.bash
Labels: bug, build
