Repository ccache/ccache, pull requests merged in 2020-11, with the labels that each got.

#706 Fall back to version "unknown" when Git is not installed
  cmake/CcacheVersion.cmake
Labels: build, improvement

#693 Disable some tests on ancient Clang versions
  dockerfiles/ubuntu-14.04/Dockerfile
  test/suites/modules.bash
  test/suites/profiling.bash
  test/suites/profiling_clang.bash
  test/suites/profiling_hip_clang.bash
  test/suites/sanitize_blacklist.bash
  test/suites/serialize_diagnostics.bash
  test/suites/split_dwarf.bash
Labels: improvement, portability, test

#723 Link with libatomic when needed
  cmake/StandardSettings.cmake
  cmake/StdAtomic.cmake
Labels: bug, build, portability

#685 Cache result even without object file
  src/ArgsInfo.hpp
  src/argprocessing.cpp
  src/ccache.cpp
  test/suites/base.bash
  unittest/test_argprocessing.cpp
Labels: feature

#722 Fix result_name_from_depfile by parsing depfile in Makefile syntax
  src/ccache.cpp
  src/ccache.hpp
  unittest/test_ccache.cpp
Labels: bug

#733 Github: Call apt-get update before install
  .github/workflows/build.yaml
Labels: ci, improvement

#732 MinGW: Default to static linking
  .github/workflows/build.yaml
  CMakeLists.txt
Labels: build, improvement
