Repository ccache/ccache, pull requests merged in 2020-10, with the labels that each got.

#663 Refactor: slightly improve naming in compopt
  src/argprocessing.cpp
  src/ccache.cpp
  src/compopt.cpp
  src/compopt.hpp
  unittest/test_compopt.cpp
Labels: improvement

#677 Disable some new clang-tidy features until they are fixed
  src/.clang-tidy
Labels: improvement

#678 Add unittests to parsing -x
  src/argprocessing.cpp
  unittest/test_argprocessing.cpp
Labels: improvement

#664 Make CCACHE_COMPILER always the highest priority
  src/ccache.cpp
  test/suites/base.bash
  unittest/test_ccache.cpp
Labels: feature

#679 Remove -lgcov from compiler independent profiling script
  test/suites/profiling.bash
  test/suites/profiling_gcc.bash
Labels: bug, test

#681 Fix expect_perm to work with SELinux
  test/run
Labels: bug, test

#687 Support ccache ccache gcc
  src/ccache.cpp
  test/suites/base.bash
  unittest/test_ccache.cpp
Labels: bug

#691 Add missing parameters to log() call
  src/Util.cpp
Labels: bug

#692 Blake3: use C version on ancient clang
  src/third_party/blake3/CMakeLists.txt
Labels: bug, build

#696 Use BLAKE3 machinery for detecting AVX2 support
  cmake/GenerateConfigurationFile.cmake
  src/hashutil.cpp
  src/third_party/blake3/CMakeLists.txt
  src/third_party/blake3/blake3_cpu_supports_avx2.h
  src/third_party/blake3/blake3_dispatch_ccache.c
Labels: bug, build

#694 Require CLONE_NOOWNERCOPY to be defined for clone on mac
  src/Util.cpp
Labels: build, test

#699 Fix order of commands in third_party cmake
  src/third_party/CMakeLists.txt
Labels: bug, portability

#702 Fail gracefully on ancient compilers
  CMakeLists.txt
Labels: build, improvement, portability

#690 CI: list all configurations explicitly
  .github/workflows/build.yaml
  CMakeLists.txt
Labels: ci, improvement

#705 Build and install man page by default
  doc/CMakeLists.txt
Labels: bug, build

#704 Disable some AVX features on old Apple clang versions
  cmake/GenerateConfigurationFile.cmake
  cmake/StandardSettings.cmake
  src/third_party/blake3/CMakeLists.txt
Labels: build, improvement, portability

#712 MinGW: Fix static linkage with gcc and libstdc++ and make it optional
  .github/workflows/build.yaml
  CMakeLists.txt
  src/CMakeLists.txt
Labels: build, improvement, windows
