Repository ccache/ccache, pull requests merged in 2021-08, with the labels that each got.

#911 docs: Fix links to section anchors
  doc/MANUAL.adoc
  doc/NEWS.adoc
Labels: documentation, improvement

#910 docs: Add scheme to link to fonts.googleapis.com
  doc/ccache-doc.css
Labels: documentation, improvement

#912 Add support for cache sharding on secondary storage
  doc/MANUAL.adoc
  src/storage/Storage.cpp
  src/storage/secondary/SecondaryStorage.cpp
  test/suites/secondary_file.bash
Labels: feature

#913 build: Link ws2_32 to third_party instead of ccache_framework
  src/CMakeLists.txt
  src/third_party/CMakeLists.txt
Labels: bug, windows, build

#925 fix(test): Pass all three required arguments to expect_file_count
  test/run
  test/suites/secondary_file.bash
Labels: bug, test

#918 Fix linker and IPO handling on various platforms
  .github/workflows/build.yaml
  CMakeLists.txt
  cmake/UseFastestLinker.cmake
Labels: bug, build
