Repository ccache/ccache, pull requests merged in 2021-02, with the labels that each got.

#800 StdAtomic.cmake: probe atomic increment as well
  cmake/StdAtomic.cmake
Labels: build, portability

#802 Support -fcolor-diagnostics passed to cc1 with -Xclang
  src/argprocessing.cpp
  test/suites/color_diagnostics.bash
  unittest/test_argprocessing.cpp
Labels: bug

#805 Build ccache with xlclang++ on AIX72
  cmake/config.h.in
  src/ccache.cpp
  src/system.hpp
  unittest/test_Util.cpp
Labels: build, improvement, portability

#808 Fix Util::read_file returning truncated results if size_hint is an underestimate
  src/Util.cpp
  unittest/test_Util.cpp
Labels: bug, windows
