Repository ccache/ccache, pull requests merged in 2021-04, with the labels that each got.

#832 Stat: treat pending deletes as missing files on Windows
  .github/workflows/build.yaml
  src/Stat.cpp
  src/Win32Util.cpp
  src/Win32Util.hpp
  src/system.hpp
  unittest/test_Stat.cpp
Labels: bug, windows

#838 Fix performance impact from 'Canonicalize path for comparison; Clang …
  src/ccache.cpp
Labels: bug

#839 Ignore -ivfsoverlay parameter
  doc/MANUAL.adoc
  src/Config.cpp
  src/Sloppiness.hpp
  src/argprocessing.cpp
  src/compopt.cpp
  test/CMakeLists.txt
  test/suites/ivfsoverlay.bash
  unittest/test_Config.cpp
Labels: improvement

#840 Fix detection of pthread features
  cmake/GenerateConfigurationFile.cmake
Labels: bug, build, portability
