Repository ccache/ccache, pull requests merged in 2021-11, with the labels that each got.

#953 fix: Correct win32 log messages about file locks
  src/Lockfile.cpp
  src/Win32Util.cpp
Labels: bug, windows

#955 fix: Correct debug dir handling on Windows
  src/ccache.cpp
  src/util/path.cpp
  src/util/path.hpp
  unittest/test_util_path.cpp
Labels: bug, windows

#506 Visual C/C++ compiler support
  misc/codespell-allowlist.txt
  src/Args.cpp
  src/Args.hpp
  src/Config.cpp
  src/Config.hpp
  src/argprocessing.cpp
  src/ccache.cpp
  src/compopt.cpp
  unittest/test_Args.cpp
Labels: feature, os: windows

#963 fix: Make AVX2 code work also with MSVC
  cmake/GenerateConfigurationFile.cmake
  src/hashutil.cpp
Labels: portability, improvement, compiler: msvc

#964 fix: Use default object file extension .obj for MSVC
  src/argprocessing.cpp
Labels: bug, compiler: msvc

#968 fix: handle newlines on Windows properly
  src/Util.cpp
  src/Util.hpp
Labels: bug, os: windows

#970 fix: Ignore CCACHE_NOCPP2=1 with MSVC
  doc/MANUAL.adoc
  src/ccache.cpp
Labels: bug, compiler: msvc
