Repository ccache/ccache, pull requests merged in 2021-06, with the labels that each got.

#854 Add stats log file, logging input file and result
  doc/MANUAL.adoc
  src/Config.cpp
  src/Config.hpp
  src/Statistics.cpp
  src/Statistics.hpp
  src/ccache.cpp
  unittest/test_Config.cpp
  unittest/test_Statistics.cpp
Labels: feature

#862 Ignore CLion IDE files
  .gitignore
Labels: improvement

#861 Explicitly select C++ when using -fcxx-modules
  test/suites/modules.bash
Labels: improvement, test

#867 Skip nvcc_ldir test with non-working nvcc.
  test/suites/nvcc_ldir.bash
Labels: improvement, portability, test

#868 Add sloppy include_file_mtime to ivfsoverlay test
  test/suites/ivfsoverlay.bash
Labels: improvement, portability, test

#869 Put compile option with args into quotes
  cmake/StandardSettings.cmake
Labels: build, improvement, portability

#874 Allow one -Xarch_* option that matches -arch
  src/argprocessing.cpp
  test/suites/multi_arch.bash
Labels: feature
