Repository ccache/ccache, pull requests merged in 2021-01, with the labels that each got.

#760 Make Util::make_relative_path able to find matches for canonical path
  src/Util.cpp
  unittest/test_Util.cpp
Labels: bug, portability

#757 CI: Add VS2019 build jobs
  .github/workflows/build.yaml
  cmake/CIBuildType.cmake
  cmake/DevModeWarnings.cmake
Labels: ci, improvement, windows

#758 Fix scanning of headers with clang-tidy
  src/.clang-tidy
  src/CMakeLists.txt
  src/Config.hpp
  src/NonCopyable.hpp
  src/argprocessing.hpp
  src/third_party/CMakeLists.txt
  unittest/CMakeLists.txt
Labels: ci, improvement

#755 Ignore SOURCE_DATE_EPOCH under time_macros sloppiness
  doc/MANUAL.adoc
  src/ccache.cpp
  test/suites/base.bash
Labels: feature

#762 Always use 64bit to print time_t
  src/Logging.cpp
Labels: bug, portability

#763 CI: Fix testdir upload file name in case of failed tests
  .github/workflows/build.yaml
Labels: ci

#769 Fix Lockfile on Windows when parent directories do not exist
  src/Lockfile.cpp
  unittest/test_Lockfile.cpp
Labels: bug, windows

#746 Add CodeQL
  .github/workflows/codeql-analysis.yaml
Labels: ci, improvement

#761 doc/MANUAL.adoc: don't use non-ASCII quotes
  doc/MANUAL.adoc
Labels: bug, build, documentation

#759 Faster compile times
  CMakeLists.txt
  cmake/UseCcache.cmake
  cmake/UseFastestLinker.cmake
  doc/CMakeLists.txt
Labels: build, improvement

#764 Extract enums into separate headers
  src/Config.cpp
  src/Context.hpp
  src/Counters.cpp
  src/Manifest.cpp
  src/Result.cpp
  src/Sloppiness.hpp
  src/Statistic.hpp
  src/Statistics.hpp
  src/argprocessing.hpp
  src/ccache.cpp
  src/ccache.hpp
  src/cleanup.cpp
  src/exceptions.hpp
  src/hashutil.cpp
  unittest/test_Config.cpp
  unittest/test_Counters.cpp
  unittest/test_Statistics.cpp
  unittest/test_argprocessing.cpp
  unittest/test_ccache.cpp
Labels: improvement

#779 Refactor: drop out parameter from get_level_1_files
  src/CacheFile.hpp
  src/Util.cpp
  src/Util.hpp
  src/cleanup.cpp
  src/compress.cpp
  unittest/test_Util.cpp
Labels: improvement

#780 Test suite fixes and improvements for Windows
  test/run
  test/suites/base.bash
  test/suites/cleanup.bash
  test/suites/inode_cache.bash
Labels: improvement, test, windows

#788 Fix fast linker selection for old gcc versions
  .github/workflows/build.yaml
  cmake/UseFastestLinker.cmake
Labels: bug, build

#789 Tests: improve COFF object file comparison
  .github/workflows/build.yaml
  test/run
Labels: ci, improvement, windows

#790 CI: skip homebrew update/cleanup on macOS
  .github/workflows/build.yaml
Labels: ci, improvement

#791 disable inode cache on OS without pthread_mutexattr_setpshared()
  CMakeLists.txt
  cmake/GenerateConfigurationFile.cmake
  cmake/config.h.in
  src/system.hpp
Labels: bug, build, portability
