Repository ccache/ccache, pull requests merged in 2021-12, with the labels that each got.

#962 Add support for caching stdout from MSVC
  doc/MANUAL.adoc
  src/Result.cpp
  src/Result.hpp
  src/ResultRetriever.cpp
  src/ccache.cpp
  test/suites/base.bash
Labels: feature, compiler: msvc

#954 Fix and simplify handling of options for MSVC
  src/argprocessing.cpp
  src/compopt.cpp
Labels: compiler: msvc

#972 MSVC's -link option is too hard
  src/compopt.cpp
Labels: bug, compiler: msvc

#979 Fix copying of binary files on Windows
  src/Util.cpp
  test/suites/secondary_file.bash
  unittest/test_Util.cpp
Labels: bug, os: windows

#981 fix: Remove duplicate -Xarch second argument
  src/argprocessing.cpp
  test/suites/multi_arch.bash
Labels: bug, os: macos

#983 fix: avoid .incbin false positive
  src/ccache.cpp
  test/suites/base.bash
Labels: bug
