Repository ccache/ccache, pull requests merged in 2021-05, with the labels that each got.

#842 CMake: make build of documentation optional
  CMakeLists.txt
Labels: build, improvement

#843 Support `-specs file.specs` and `--specs file.specs`
  src/ccache.cpp
  src/compopt.cpp
Labels: improvement

#850 Add support for clang's --config option
  src/ccache.cpp
  src/compopt.cpp
Labels: new compiler behavior

#852 Enable minitrace tracing and stop it from crashing
  src/MiniTrace.cpp
  src/MiniTrace.hpp
  src/third_party/CMakeLists.txt
Labels: bug
