Repository ccache/ccache, pull requests merged in 2021-07, with the labels that each got.

#873 fix: AppleClang detection
  test/run
  test/suites/direct_gcc.bash
Labels: bug, portability, test

#878 Use generator expression for ccache location
  test/CMakeLists.txt
Labels: bug, build

#879 Allow dumping stdin by giving - as path
  doc/MANUAL.adoc
  src/Manifest.cpp
  src/Result.cpp
Labels: improvement

#880 Add magic file, for identifying ccache files
  misc/ccache.magic
Labels: improvement

#883 Fix CMake feature detection
  CMakeLists.txt
  cmake/GenerateConfigurationFile.cmake
Labels: build, improvement, portability

#882 Globally define WIN32_LEAN_AND_MEAN
  cmake/StandardSettings.cmake
  src/system.hpp
  src/third_party/win32/mktemp.c
Labels: build, improvement, windows

#885 Require CMake 3.10
  CMakeLists.txt
  cmake/CcachePackConfig.cmake
  cmake/CodeAnalysis.cmake
  test/CMakeLists.txt
Labels: build, improvement, portability

#881 Use URL class for URL parsing
  LICENSE.adoc
  src/storage/Storage.cpp
  src/storage/Storage.hpp
  src/storage/secondary/FileStorage.cpp
  src/storage/secondary/FileStorage.hpp
  src/third_party/CMakeLists.txt
  src/third_party/url.cpp
  src/third_party/url.hpp
  test/CMakeLists.txt
  test/suites/secondary_url.bash
Labels: improvement

#886 Update dockerfiles with supported distributions
  dockerfiles/alpine-3.14/Dockerfile
  dockerfiles/alpine-3.8/Dockerfile
  dockerfiles/centos-8/Dockerfile
  dockerfiles/debian-11/Dockerfile
  dockerfiles/debian-9/Dockerfile
  misc/test-all-systems
  src/storage/secondary/FileStorage.hpp
  src/util/string_utils.hpp
Labels: build, improvement, portability

#676 Add secondary HTTP storage
  .github/workflows/build.yaml
  LICENSE.adoc
  doc/MANUAL.adoc
  src/ccache.hpp
  src/storage/Storage.cpp
  src/storage/secondary/CMakeLists.txt
  src/storage/secondary/HttpStorage.cpp
  src/storage/secondary/HttpStorage.hpp
  src/third_party/httplib.h
  test/CMakeLists.txt
  test/http-client
  test/http-server
  test/run
  test/suites/secondary_http.bash
Labels: feature

#875 Add optional Redis secondary storage backend
  .github/workflows/build.yaml
  .github/workflows/codeql-analysis.yaml
  CMakeLists.txt
  cmake/Findhiredis.cmake
  doc/MANUAL.adoc
  misc/upload-redis
  src/CMakeLists.txt
  src/storage/Storage.cpp
  src/storage/secondary/CMakeLists.txt
  src/storage/secondary/RedisStorage.cpp
  src/storage/secondary/RedisStorage.hpp
  test/CMakeLists.txt
  test/suites/secondary_redis.bash
Labels: feature

#891 Only run redis test if backend is enabled
  test/CMakeLists.txt
Labels: improvement, test

#895 Add secondary HTTP authentication
  doc/MANUAL.adoc
  src/storage/secondary/HttpStorage.cpp
  test/http-client
  test/http-server
  test/suites/secondary_http.bash
Labels: feature

#896 HTTP storage: Implement timeout support
  doc/MANUAL.adoc
  src/storage/secondary/HttpStorage.cpp
  src/storage/secondary/HttpStorage.hpp
Labels: feature

#897 Expose list of enabled features
  src/ccache.cpp
  test/CMakeLists.txt
  test/suites/secondary_redis.bash
Labels: improvement, test

#901 Fix test-all-systems
  dockerfiles/alpine-3.14/Dockerfile
  dockerfiles/alpine-3.8/Dockerfile
  dockerfiles/centos-7/Dockerfile
  dockerfiles/centos-8/Dockerfile
  dockerfiles/debian-10/Dockerfile
  dockerfiles/debian-11/Dockerfile
  dockerfiles/fedora-32/Dockerfile
  dockerfiles/ubuntu-18.04/Dockerfile
  dockerfiles/ubuntu-20.04/Dockerfile
  misc/test-all-systems
  src/Util.cpp
Labels: improvement, test

#898 HTTP storage: Fix IPv6 address handling
  LICENSE.adoc
  doc/MANUAL.adoc
  src/storage/secondary/HttpStorage.cpp
  src/third_party/httplib.h
  test/suites/secondary_http.bash
Labels: bug

#903 Derive ccache featues from storage registry
  src/ccache.cpp
  src/storage/Storage.cpp
  src/storage/Storage.hpp
Labels: improvement

#905 Use cpp-httplib 0.9.2
  LICENSE.adoc
  src/storage/secondary/HttpStorage.cpp
  src/third_party/httplib.h
Labels: improvement

#909 Disable preprocessor hits for PCHs with clang again
  src/ccache.cpp
Labels: bug
