Repository ccache/ccache, pull requests merged in 2021-03, with the labels that each got.

#807 Fix "Debug option" test
  test/suites/base.bash
Labels: bug, test

#813 Build: don't enable ccache when building with MSVC
  cmake/UseCcache.cmake
Labels: bug, build, windows

#814 test: print line number of failing assert
  test/run
Labels: improvement, test

#819 Implement a better Stat::stat(), Stat::lstat() for Windows
  LICENSE.adoc
  src/Stat.cpp
  src/Stat.hpp
  src/system.hpp
  src/third_party/win32/winerror_to_errno.h
  unittest/test_Stat.cpp
Labels: bug, windows

#816 Fix win32execute
  src/Win32Util.cpp
  src/Win32Util.hpp
  src/ccache.cpp
  src/execute.cpp
  src/execute.hpp
  src/system.hpp
  unittest/test_Win32Util.cpp
Labels: bug, windows

#830 Changed zstd url back to http
  doc/INSTALL.md
Labels: documentation, improvement
