Repository ccache/ccache, pull requests merged in 2021-09, with the labels that each got.

#924 Fix build errors with clang on Windows
  src/Config.cpp
  unittest/test_Win32Util.cpp
Labels: windows, portability, improvement, build

#927 fix(http-storage): Disable broken connection keep-alive
  src/storage/secondary/HttpStorage.cpp
Labels: bug

#928 fix: Always store configuration origin value
  src/Config.cpp
  test/CMakeLists.txt
  test/suites/config.bash
Labels: bug

#933 Use shell builtin pwd for basedir test
  test/suites/basedir.bash
Labels: bug, portability, test
