Repository ccache/ccache, pull requests merged in 2022-10, with the labels that each got.

#1168 feat: Add sloppiness for -frandom-seed
  doc/MANUAL.adoc
  src/Config.cpp
  src/ccache.cpp
  src/core/Sloppiness.hpp
Labels: feature

#1171 fix: Fix implementation of unsetenv on Windows
  src/Util.cpp
Labels: bug, os: windows

#1169 build: Use pkgconfig for zstd search
  cmake/Findzstd.cmake
Labels: improvement, build

#1158 feat: Support auto depend mode for MSVC without /showIncludes
  src/ArgsInfo.hpp
  src/Config.cpp
  src/Config.hpp
  src/Context.hpp
  src/argprocessing.cpp
  src/ccache.cpp
  src/core/CMakeLists.txt
  src/core/ResultRetriever.cpp
  src/core/ShowIncludesParser.cpp
  src/core/ShowIncludesParser.hpp
  unittest/test_Config.cpp
Labels: feature, compiler: msvc

#1173 fix: Store output without line-ending conversion
  src/ccache.cpp
Labels: bug, os: windows

#1174 feat: add depend mode tests
  test/suites/depend.bash
Labels: improvement, test

#1166 fix: spaces between target and colon in dependency files
  src/Depfile.cpp
  unittest/test_Depfile.cpp
Labels: bug

#1172 fix: Remove usage of deprecated codecvt header
  src/util/file.cpp
  unittest/test_util_file.cpp
Labels: os: windows, improvement

#992 feat: Support depend mode for MSVC
  doc/MANUAL.adoc
  src/ArgsInfo.hpp
  src/Config.cpp
  src/Config.hpp
  src/argprocessing.cpp
  src/ccache.cpp
  src/core/CMakeLists.txt
  src/core/ShowIncludesParser.cpp
  src/core/ShowIncludesParser.hpp
  unittest/CMakeLists.txt
  unittest/test_Config.cpp
  unittest/test_core_ShowIncludesParser.cpp
Labels: feature, compiler: msvc

#1133 Make the tests work under Windows
  .github/workflows/build.yaml
  test/run
  test/suites/base.bash
  test/suites/basedir.bash
  test/suites/color_diagnostics.bash
  test/suites/cpp1.bash
  test/suites/debug_prefix_map.bash
  test/suites/depend.bash
  test/suites/direct.bash
  test/suites/hardlink.bash
  test/suites/modules.bash
  test/suites/nocpp2.bash
  test/suites/pch.bash
  test/suites/profiling.bash
  test/suites/profiling_gcc.bash
  test/suites/remote_file.bash
  test/suites/remote_http.bash
  test/suites/remote_only.bash
  test/suites/remote_url.bash
  test/suites/serialize_diagnostics.bash
  test/suites/split_dwarf.bash
  test/suites/upgrade.bash
Labels: os: windows, improvement, test

#1179 build: Remove clang64 msys target from ci
  .github/workflows/build.yaml
Labels: ci, improvement

#1176 feat: Support auto depend mode for MSVC without /showIncludes
  doc/MANUAL.adoc
  src/Config.hpp
  src/Context.hpp
  src/argprocessing.cpp
  src/ccache.cpp
  src/core/ResultRetriever.cpp
  src/core/ShowIncludesParser.cpp
  src/core/ShowIncludesParser.hpp
  unittest/test_core_ShowIncludesParser.cpp
Labels: feature, compiler: msvc

#1178 build: Add headers to CMake project files
  src/CMakeLists.txt
  src/core/CMakeLists.txt
  src/storage/CMakeLists.txt
  src/storage/local/CMakeLists.txt
  src/storage/remote/CMakeLists.txt
  src/third_party/CMakeLists.txt
  src/third_party/blake3/CMakeLists.txt
  src/util/CMakeLists.txt
  unittest/CMakeLists.txt
Labels: improvement, build

#1180 build: Remove Ubuntu 18.04 image from ci
  .github/workflows/build.yaml
Labels: ci, improvement

#1190 build: Fix compilation with GCC 8
  cmake/StandardSettings.cmake
  cmake/StdFilesystem.cmake
Labels: improvement, build

#1191 build: Remove unneeded C++11 flag in libatomic test
  cmake/StdAtomic.cmake
Labels: improvement, build

#1195 build: apply standard settings and warnings to lockfile test
  src/CMakeLists.txt
Labels: os: windows, improvement, build

#1199 fix: Process the argument following a -Xarch argument
  src/argprocessing.cpp
  test/suites/multi_arch.bash
Labels: bug, os: macos
