Repository ccache/ccache, pull requests merged in 2022-11, with the labels that each got.

#1221 fix: Do not create /run directory on systems that don't have it when …
  src/Config.cpp
Labels: bug, os: freebsd

#1222 fix: posix_fallocate can return EINVAL if filesystem doesn't support …
  src/Util.cpp
Labels: bug, portability

#1227 fix: Fix edge case where a non-temporal identifier is misidentified
  src/hashutil.cpp
  unittest/test_hashutil.cpp
Labels: bug
