Repository ccache/ccache, pull requests merged in 2022-01, with the labels that each got.

#988 Fix stats output for secondary storage
  src/core/Statistics.cpp
Labels: bug

#991 support MSVC /Yu option (compiling with PCH)
  src/argprocessing.cpp
  src/compopt.cpp
Labels: feature, compiler: msvc

#973 Fix upload-redis after cache entry format change
  misc/upload-redis
Labels: improvement

#995 MSVC's -Zs is GCC's -fsyntax-only
  src/argprocessing.cpp
Labels: feature, compiler: msvc

#994 do not handle -o<file> for MSVC
  src/argprocessing.cpp
Labels: bug, compiler: msvc

#1000 feat: Enable HTTP keep-alive by default
  doc/MANUAL.adoc
  src/storage/secondary/HttpStorage.cpp
Labels: feature

#1001 feat: Add option to use Bearer token with HTTP backend
  doc/MANUAL.adoc
  src/storage/secondary/HttpStorage.cpp
Labels: feature
