Repository ccache/ccache, pull requests merged in 2022-08, with the labels that each got.

#1124 fix: Move Windows config and cache to LOCALAPPDATA
  CMakeLists.txt
  cmake/GenerateConfigurationFile.cmake
  cmake/InstallDirs.cmake
  cmake/config.h.in
  doc/MANUAL.adoc
  src/Config.cpp
  src/Util.cpp
  src/Util.hpp
Labels: os: windows, improvement

#1132 fix: Fix Clang/Windows build
  CMakeLists.txt
  src/util/LockFile.cpp
Labels: os: windows, build

#1134 test: Add version output on failure
  test/suites/base.bash
Labels: test

#1135 fix: Strip .exe from executable name on version output
  src/core/mainoptions.cpp
Labels: bug, os: windows

#1145 Fix build with musl when using gcc12
  src/Config.hpp
  src/core/Statistics.hpp
Labels: bug, portability, build
