Repository ccache/ccache, pull requests merged in 2022-07, with the labels that each got.

#1064 Support Redis over unix socket
  doc/MANUAL.adoc
  src/storage/Storage.cpp
  src/storage/secondary/RedisStorage.cpp
  test/CMakeLists.txt
  test/suites/secondary_redis_unix.bash
Labels: feature

#1111 Add download-redis script matching the upload-redis
  misc/download-redis
Labels: improvement

#1112 feat: auto dep FROM_INTERNET when unavailable
  CMakeLists.txt
  cmake/Findhiredis.cmake
  cmake/Findzstd.cmake
  src/CMakeLists.txt
Labels: feature, build
