Repository ccache/ccache, pull requests merged in 2022-04, with the labels that each got.

#1043 fix: Add ASM and ASM_MASM to project() languages
  CMakeLists.txt
Labels: bug, portability, build

#1037 fix: Do not add redundant newlines for stdout
  src/Util.cpp
  src/Util.hpp
  src/ccache.cpp
  src/util/Tokenizer.cpp
  src/util/Tokenizer.hpp
  unittest/test_util_Tokenizer.cpp
Labels: bug

#1046 fix: Replace skip_last_empty with IncludeDelimiter
  src/Depfile.cpp
  src/Util.cpp
  src/util/Tokenizer.cpp
  src/util/Tokenizer.hpp
  unittest/test_util_Tokenizer.cpp
Labels: bug

#1041 fix: Fix static linkage with hiredis on Windows
  cmake/Findhiredis.cmake
Labels: bug, os: windows, build

#1033 fix: normalize abs paths when collecting includes to fix basedir option
  src/ArgsInfo.hpp
  src/argprocessing.cpp
  src/ccache.cpp
Labels: bug, os: windows
