Repository ccache/ccache, pull requests merged in 2022-03, with the labels that each got.

#1020 Authenticate Redis before database selection
  src/storage/secondary/RedisStorage.cpp
Labels: bug

#1036 Fix ccache: error: Failed to read from file stream
  src/ccache.cpp
Labels: bug

#1019 msvc: support directory input for -Fo
  src/argprocessing.cpp
Labels: feature, compiler: msvc

#1030 fix: Prefer CMake find module for zstd package
  CMakeLists.txt
Labels: bug, build

#1031 docs: Add reference to reference build configs
  doc/INSTALL.md
Labels: documentation, improvement
