Repository ccache/ccache, pull requests merged in 2022-05, with the labels that each got.

#1056 Fix sporatic test.profiling failures
  test/suites/profiling.bash
Labels: bug, test

#1054 build: Fix build arguments to clang-cl
  cmake/StandardSettings.cmake
Labels: bug, build, compiler: clang-cl

#1055 Handle -imsvc compiler option
  src/compopt.cpp
Labels: feature, compiler: clang-cl

#1059 Fix "Multiple precompiled headers used" error if /Yu option is used after /Fp
  src/argprocessing.cpp
Labels: bug, compiler: msvc

#1068 fix: Check for short reads in Reader::read_str
  src/core/Reader.hpp
Labels: bug

#1053 fix: Fix miscompile of nonstd::expected on MSVC v19.22
  src/third_party/nonstd/expected.hpp
Labels: bug, os: windows, portability, compiler: msvc

#1071 fix: Fix parsing of MSVC response files
  src/Args.cpp
  src/Args.hpp
  src/argprocessing.cpp
  unittest/test_Args.cpp
Labels: bug, compiler: msvc, compiler: clang-cl

#1075 fix: Skip empty files names in preprocessor output
  src/ccache.cpp
Labels: bug

#1080 fix(win32execute): Handle space in paths when using response file
  src/execute.cpp
Labels: bug, os: windows
