Repository ccache/ccache, pull requests merged in 2022-06, with the labels that each got.

#1058 feat: Generalize STATIC_LINK option + fixes
  CMakeLists.txt
  src/CMakeLists.txt
Labels: os: windows, improvement, build

#1065 feat: Fetch/update secondary storage manifest on primary miss
  src/ccache.cpp
  src/storage/Storage.cpp
  src/storage/Storage.hpp
Labels: feature

#1093 build: Fix build with newer MSVC 2022 versions
  src/core/exceptions.hpp
Labels: portability, build, compiler: msvc
