Repository ccache/ccache, pull requests merged in 2022-02, with the labels that each got.

#993 Detect clang-cl as a compiler
  src/Config.cpp
  src/Config.hpp
  src/argprocessing.cpp
  src/ccache.cpp
Labels: feature, compiler: msvc

#1003 Fix clang-cl display name
  src/Config.cpp
Labels: bug, compiler: clang-cl

#1006 Add documentation that compiler plugins are hashed too
  doc/MANUAL.adoc
Labels: documentation

#1005 fix: Support UTF-16LE .rsp files
  src/Args.cpp
  src/Util.cpp
  src/Util.hpp
  unittest/test_Util.cpp
Labels: bug, os: windows

#1011 fix: Make conversion to relative paths more reliable on Windows
  src/Util.cpp
  src/Util.hpp
  src/argprocessing.cpp
  src/util/path.cpp
  src/util/path.hpp
  unittest/test_Util.cpp
  unittest/test_util_path.cpp
Labels: bug, os: windows
