Repository ccache/ccache, pull requests merged in 2022-09, with the labels that each got.

#1157 refactor: Reuse local reference in process_args
  src/argprocessing.cpp
Labels: improvement

#1159 ci: Add minimum GitHub token permissions for workflows
  .github/workflows/build.yaml
  .github/workflows/codeql-analysis.yaml
Labels: ci, improvement

#1161 fix: small typo in the run script
  test/run
Labels: bug, test

#1167 test: Fix typo in depend tests
  test/suites/depend.bash
Labels: improvement, test

#1165 feat: add support for -external:I for msvc
  src/compopt.cpp
Labels: bug, compiler: msvc
