Repository ccache/ccache, pull requests merged in 2023-06, with the labels that each got.

#1290 Fix MSBuild CI jobs + minor cmake fixes
  .github/workflows/build.yaml
  CMakeSettings.json
  LICENSE.adoc
  cmake/Findhiredis.cmake
  cmake/Findzstd.cmake
  src/third_party/blake3/CMakeLists.txt
  src/third_party/blake3/blake3.c
  src/third_party/blake3/blake3.h
  src/third_party/blake3/blake3_avx2_x86-64_windows_gnu.S
  src/third_party/blake3/blake3_avx512.c
  src/third_party/blake3/blake3_avx512_x86-64_windows_gnu.S
  src/third_party/blake3/blake3_dispatch.c
  src/third_party/blake3/blake3_impl.h
  src/third_party/blake3/blake3_sse2_x86-64_windows_gnu.S
  src/third_party/blake3/blake3_sse41_x86-64_windows_gnu.S
Labels: ci, improvement, build

#1295 fix: Keep the order of MSVC showIncludes output
  src/ccache.cpp
Labels: bug, compiler: msvc

#1296 build: fix Xcode build of zstd
  cmake/Findzstd.cmake
Labels: bug, build, os: macos

#1297 refactor: Use std::size to compute array size
  src/core/Statistics.cpp
Labels: improvement

#1298 feat: Don't hash /Fd, /FS and /MP
  src/argprocessing.cpp
Labels: feature, compiler: msvc

#1303 fix: Improve handling of backslash in MSVC .rsp
  src/Args.cpp
  unittest/test_Args.cpp
Labels: bug, compiler: msvc

#1304 fix: How nvcc handles host warnings by adding Xcompiler and --Werror.
  src/compopt.cpp
  unittest/test_argprocessing.cpp
Labels: bug, compiler: nvcc
