Repository ccache/ccache, pull requests merged in 2023-07, with the labels that each got.

#1307 feat: Expand environment variables in debug_dir configuration entry
  src/Config.cpp
  unittest/test_Config.cpp
Labels: feature

#1274 win32: automatically kill compiler subprocess
  src/execute.cpp
Labels: feature, os: windows

#1131 feat: Support multiple -Xarch_* arguments matching -arch
  src/ArgsInfo.hpp
  src/argprocessing.cpp
  src/ccache.cpp
  test/suites/multi_arch.bash
Labels: feature, os: macos
