Repository ccache/ccache, pull requests merged in 2023-10, with the labels that each got.

#1331 fix: src/InodeCache.cpp: avoid sign-compare warning on FreeBSD
  src/InodeCache.cpp
Labels: improvement, build, os: freebsd

#1338 fix: Windows is_absolute_path() crash on drive letter
  src/util/path.cpp
  unittest/test_util_path.cpp
Labels: bug, os: windows

#1340 fix: cmake -DSTATIC_LINK=ON on Linux/macOS
  CMakeLists.txt
  cmake/StaticLinkSupport.cmake
Labels: improvement, build

#1341 feat: cmake -DOFFLINE=TRUE for offline builds
  CMakeLists.txt
  cmake/Findhiredis.cmake
  cmake/Findzstd.cmake
  doc/INSTALL.md
Labels: improvement, build

#1342 fix: devmode unused function warnings on new MSVC
  cmake/DevModeWarnings.cmake
Labels: improvement, build, compiler: msvc
