Repository ccache/ccache, pull requests merged in 2023-11, with the labels that each got.

#1345 (feat)add support for clang --analyze
  src/argprocessing.cpp
  src/compopt.cpp
  unittest/test_compopt.cpp
Labels: feature, compiler: clang

#1348 fix: Detect symlink called clang-cl as clang-cl insted of normal clang
  src/ccache.cpp
Labels: bug

#1357 Fix regexp in direct.bash
  test/suites/direct.bash
Labels: bug, test

#1359 Use GHA feature in build.yaml
  .github/workflows/build.yaml
Labels: ci, improvement

#1360 Remove matrix.config from build.yaml
  .github/workflows/build.yaml
Labels: ci, improvement

#1358 Properly exclude false positive typos
  misc/typos.toml
Labels: improvement

#1365 fix: Use MSVC logic for clang-cl when handling precompiled header
  src/argprocessing.cpp
Labels: bug, compiler: clang-cl
