Repository ccache/ccache, pull requests merged in 2024-09, with the labels that each got.

#1499 feat: Add support for MSVC /TC and /TP options
  src/ccache/argprocessing.cpp
Labels: feature, compiler: msvc

#1502 fix: replace_all
  src/ccache/util/string.cpp
  unittest/test_util_string.cpp
Labels: bug

#1504 feat: Option absolute_paths_in_stderr also rewrites relative paths in MSVC diagnostics messages
  src/ccache/core/common.cpp
  src/ccache/core/common.hpp
  unittest/test_core_common.cpp
Labels: feature, os: windows, compiler: msvc

#1506 refactor: Remove duplicated call to posix_spawn_file_actions_init
  src/ccache/hashutil.cpp
Labels: improvement

#1508 build: Instruct MSVC to accept UTF-8 characters
  cmake/StandardSettings.cmake
Labels: portability, improvement, build, compiler: msvc

#1509 feat: Relativize absolute paths within base_dir in MSVC diagnostics messages
  src/ccache/ccache.cpp
Labels: feature, compiler: msvc

#1510 fix(http-storage): Make sure 'keep-alive' can be overridden as expected
  src/ccache/storage/remote/httpstorage.cpp
Labels: bug

#1517 test: Add a unittest for the hard link based compiler detection
  unittest/test_ccache.cpp
Labels: improvement, test

#1515 feat: Add support for -fprofile-prefix-path gcc option (#1507)
  src/ccache/argprocessing.cpp
  src/ccache/argsinfo.hpp
  src/ccache/ccache.cpp
  test/CMakeLists.txt
  test/suites/profiling_gcc_10+.bash
Labels: feature
