Repository ccache/ccache, pull requests merged in 2024-05, with the labels that each got.

#1449 feat: add support for -fdump-ipa-clones
  src/ccache/ArgsInfo.hpp
  src/ccache/argprocessing.cpp
  src/ccache/ccache.cpp
  src/ccache/core/Result.cpp
  src/ccache/core/Result.hpp
  src/ccache/core/ResultRetriever.cpp
Labels: feature

#1448 fix: Handle -Yc without filepath for msvc
  src/ccache/argprocessing.cpp
  src/ccache/compopt.cpp
  unittest/test_argprocessing.cpp
Labels: bug, compiler: msvc

#1450 fix: Handle -Yc without -Fp and -Fo for msvc
  src/ccache/ArgsInfo.hpp
  src/ccache/argprocessing.cpp
  unittest/test_argprocessing.cpp
Labels: bug, compiler: msvc

#1453 fix: TAKES_/CONCAT_ARG for msvc options
  src/ccache/compopt.cpp
Labels: bug, compiler: msvc, compiler: clang-cl

#1454 feat: Add print-version option
  doc/MANUAL.adoc
  src/ccache/core/mainoptions.cpp
Labels: feature

#1451 perf: Use posix_spawn when hashing
  cmake/GenerateConfigurationFile.cmake
  cmake/config.h.in
  src/ccache/hashutil.cpp
Labels: improvement

#1458 feat: Add argument handling for Emscripten's --em-config
  src/ccache/compopt.cpp
Labels: feature

#1459 fix: small fixes
  src/ccache/InodeCache.cpp
  src/ccache/util/wincompat.hpp
Labels: improvement

#1460 fix: removed unused headers
  src/ccache/argprocessing.cpp
  src/ccache/ccache.cpp
Labels: improvement, build

#1461 fix: Msvc /Zc:preprocessor warning
  cmake/StandardSettings.cmake
  unittest/CMakeLists.txt
Labels: improvement, build, compiler: msvc

#1463 chore: zstd assembly fix is included in upstream version v1.5.6
  cmake/FindZstd.cmake
Labels: improvement, build

#1464 Fix detection and usage of system blake3
  cmake/FindBlake3.cmake
  src/ccache/Hash.hpp
  src/third_party/blake3/CMakeLists.txt
Labels: bug, build
