Repository ccache/ccache, pull requests merged in 2024-03, with the labels that each got.

#1408 feat: add -fprofile-update support
  src/argprocessing.cpp
  test/suites/profiling_clang.bash
  test/suites/profiling_gcc.bash
Labels: feature

#1411 fix: Hash command line argument that affect preprocessing result when…
  src/ccache.cpp
Labels: bug, compiler: msvc

#1418 Read file in do_hash_file as Bytes and optimize read_file size_hint on Windows
  src/ccache/hashutil.cpp
  src/ccache/util/file.cpp
Labels: os: windows, improvement

#1416 msys2 patch: lock mechanism uses file instead of symlink.
  src/ccache/util/LockFile.cpp
  unittest/test_Util.cpp
Labels: os: windows, portability
