Repository ccache/ccache, pull requests merged in 2024-06, with the labels that each got.

#1465 build: Fix name of CppHttplib library
  cmake/FindCppHttplib.cmake
Labels: portability

#1474 Fix finding the prefix command in the $PATH environment variable when it's not an absolute/relative path already.
  src/ccache/ccache.cpp
Labels: bug

#1471 perf: Use posix_spawn to execute the compiler
  src/ccache/execute.cpp
Labels: improvement

#1475 fix: Add the --compile option to be compliant with nvcc
  src/ccache/argprocessing.cpp
Labels: feature, compiler: nvcc
