Repository ccache/ccache, pull requests merged in 2025-01, with the labels that each got.

#1533 feat: Add support for Intel's LLVM-based compilers
  doc/MANUAL.adoc
  src/ccache/ccache.cpp
  src/ccache/config.cpp
  src/ccache/config.hpp
Labels: feature

#1548 docs: Fix description of icx-cl
  doc/MANUAL.adoc
Labels: documentation, improvement

#1549 fix: correctly call sha256sum on macOS
  misc/clang-format
Labels: improvement, os: macos, dev tools

#1535 Add support for -fdebug-compilation-dir
  doc/MANUAL.adoc
  src/ccache/argprocessing.cpp
  src/ccache/argsinfo.hpp
  src/ccache/ccache.cpp
  test/CMakeLists.txt
  test/suites/debug_compilation_dir.bash
  test/suites/debug_prefix_map.bash
Labels: feature, compiler: clang
