Repository ccache/ccache, pull requests merged in 2025-07, with the labels that each got.

#1596 feat: On a windows build, add the ccache.exe.manifest which enables l…
  CMakeLists.txt
  cmake/GenerateVersionFile.cmake
  cmake/ccache.exe.manifest.in
  cmake/version.rc.in
Labels: os: windows, improvement

#1601 Link libatomic statically when STATIC_LINK is set
  cmake/StdAtomic.cmake
Labels: build

#1612 fix: using ccache and clang to compile CUDA code on Windows results empty preprocess file
  src/ccache/ccache.cpp
Labels: bug, os: windows, compiler: clang
